### ISSUE TITLE
ETQ Usager, je ne dois pas a avoir a reconfimer l'acceptation des cgus lorsque je change de siret

### ISSUE THREAD

**Issue by LeSim** [demarche-numerique/demarche.numerique.gouv.fr#2237]
parce que des fois les gens ne le font pas (bug ou autre) et ca met le dossier dans un état invalide.
`# 4545`

voir l'utilité du `reset` dans le dossier

Autre possibilité : changer le siret et les cgus qu'une faut que l'utilisateur a sauvegardé

**Comment by tchak** [comment]
La nouvelle implementation du champ SIRET expose les informations de SIRET au navigateur avec une signature. Il est possible alors de faire un save en batch sur les données SIRET et autre informations (ici les cgu)

cc @kemenaran
