### ISSUE TITLE
Bug CSS avec prénoms si connexion FranceConnect

### ISSUE THREAD

**Issue by AntoineAugusti** [demarche-numerique/demarche.numerique.gouv.fr#2597]
Bonjour,

Une fois connecté, si je proviens de FranceConnect, on affiche mes prénoms (3 pour ma part). Ceci fait du contenu assez long, qui provoque un bug graphique.

PS : j'ai changé mes 2eme et 3eme prénoms.
![screen shot 2018-09-17 at 19 23 20](https://user-images.githubusercontent.com/295709/45639110-674ddf80-baaf-11e8-8cc5-6c49a02ecfa8.png)

**Comment by mmagn** [comment]
Merci pour l'issue !
Une nouvelle version de l'UI usager devrait corriger ce problème dans les prochains jours.
