### ISSUE TITLE
Pièces justificatives automatiquement remplacées par d'autres.

### ISSUE THREAD

**Issue by bertvoldenuit** [demarche-numerique/demarche.numerique.gouv.fr#6556]
**Décrivez le bug**
Dans le formulaire, nous devons renseigner un groupe de 12 justificatifs de domicile à nos deux noms ou un minimum de 24 justificatifs à nos noms séparément, 1 justificatif pour chaque mois. A chaque demande de TS, les pièces justificatives n° 4 et n°8 (Janvier et mai dans notre cas) ont été modifiées par le système, la première fois dans le deuxième groupe de justificatifs et la seconde fois dans le premier groupe.

**Reproduction**
Comment reproduire le problème :
1. Aller sur la page https://www.demarches-simplifiees.fr/commencer/-1eredde-pacs
2. Uploader les justificatifs dans le groupe 1
3. Créer un deuxième groupe de justificatif
4. Uploader les justificatifs dans le groupe 2
5. Créer un troisième groupe de justificatif
6. Uploader les justificatifs dans le groupe 3
7. Lors de l'examination du dossier par un instructeur, certains fichiers (ici n°4 et n°8) sont remplacés par d'autres justificatifs aléatoirement.

La même erreur a été observée deux fois.

**Comportement attendu**
Conserver tous les justificatifs dans le bon ordre.

**Capture d'écran**
![image](https://user-images.githubusercontent.com/5957713/137881982-98a8041c-8508-4575-8546-49a96988bcb3.png)

**Appareil et navigateur utilisé**
 - Appareil : PC
 - Navigateur : Firefox

**Comment by tchak** [comment]
done
