### ISSUE TITLE
Améliorer l'instruction et du traitement des dossiers

### ISSUE THREAD

**Issue by Olivier-Marcellin** [demarche-numerique/demarche.numerique.gouv.fr#7394]
Ces besoins sont rapportés par les admin du Ministère de la Culture

Priorité moyenne pour le Ministère de la Culture

Besoin 1

Élargir les possibilités d’instruction (notamment dans les subventions d’investissement pour lesquelles les pièces jointes arrivent après les versements).

Amélioration 

À prévoir une étape "en attente de x (nom document) " par exemple et un statut "Accepté sous réserve de transmission des pièces complémentaires ".

Besoin 2

• Permettre d’autoriser ou non les experts à utiliser la messagerie pour communiquer avec l’usager (ou ajouter une mention claire indiquant qu’il s’agit de la messagerie avec le demandeur) et permettre de sélectionner les éléments envoyés aux experts 

Cas d'usage

Par exemple un projet artistique, mais pas les coordonnées du représentant légal / de la personne en charge du dossier, les éléments de budget...

**Comment by LeSim** [comment]
trop compliqué, contournement possible
