### ISSUE TITLE
synchronisation de l'object storage impossible

### ISSUE THREAD

**Issue by kleph** [demarche-numerique/demarche.numerique.gouv.fr#7966]
**résumé**
La synchronisation / sauvegarde des pièces jointes dans l'object storage ne fonctionne plus vraiment.
Elle est dure trop longtemps(en dizaine d'heures) et sature la mémoire de la machine (64 Go) avant d'avoir pu finir.
Au global, la manipulation du contenu de ce bucket est difficile, voir impossible.

**détails**
On stocke les X dizaines de millions de fichiers dans le même répertoire, sans arborescence.
On utilise rclone pour faire la synchro, comme tout est dans le même répertoire, il lui faut charger l'intégralité de la liste des fichiers avant d'effectuer une comparaison.

Tout autre outil fonctionnant en mode fichier est voué à donner le même genre de résultat avec cette volumétrie.
Le mode block bas niveau n'est pas disponible de ce côté de l'API, c'est la promesse de l'abstraction object storage.

**une idée**
Une piste, possiblement naïve et totalement inspirée de la gestion des logs/artifacts/jobs de gitlab ou des volumes docker serait une arborescence basée sur des hash, dans le style :

/00/00/0000-fichier
/00/01/0001-fichier
[...]
/a0/01/a001-fichier

**Comment by mfo** [comment]
pour être certains de comprendre ; tu t'attends à ce qu'on migre toutes les PJs (RAS sur les fichiers d'ops log ?) dans des repertoires de la forme `[a-z0-9]/[a-z0-9]/`+$fileKey

et toi derriere tu backup avec rclone par segments (`[a-z0-9]/[a-z0-9]/`) pour diminuer l'emprunte mémoire ?

petite question, j'imagine qu'il y a des fichiers dont le backup n'est pas interessant ex: export/archive.

**Comment by LeSim** [comment]
Notes sur un point tech
- voir avec Object Storage comment sauvegarder avec prefix
- prevoir une migration avec un flag sur les (ActiveStorage::Blob) metadata `migrated: false`

**Comment by LeSim** [comment]
moyen terme  
acces par ip privée
sauvegarde de bucket 

concurrent a voir
aws
scaleway
outscale

**Comment by kleph** [comment]
C'est fait, et ça fonctionne, merci.
Les synchros sont encore un peu longues, mais au moins elles sont possibles maintenant !

Je clos ce ticket, on pourra discuter des prochaines étapes en dehors ou dans un autre ticket quand on sera prêt
