### ISSUE TITLE
API Entreprise: passer à la v3 avant le 01/06

### ISSUE THREAD

**Issue by colinux** [demarche-numerique/demarche.numerique.gouv.fr#8742]
On utilise encore la v2 dont le service sera interrompu le 30/06/2023

https://entreprise.api.gouv.fr/

**Comment by mfo** [comment]
je me permets d'ajouter un besoin – differencier la date de création d'une entreprise et celle de l'etablissement cf.

https://secure.helpscout.net/conversation/2222461429/2027624?folderId=1653799 
> Je me permets de vous signaler une bizarrerie dans DS et son utilisation de l'API entreprises.gouv.fr :
La date de création de l'établissement correspond à la date de création de l'entreprise et non à la date de création de l'établissement lui-même.

**Comment by krichtof** [comment]
A noter que l'API effectifs n'est pas encore implémentée en v3
Lu sur https://entreprise.api.gouv.fr/catalogue/urssaf/effectifs le 17/05/2023
> Les développements sont en cours et devraient être terminés dans les semaines à venir.

**Comment by krichtof** [comment]
[Doc de référence et tester l'api](https://api.gouv.fr/documentation/api-entreprise)

[Guide de migration](https://entreprise.api.gouv.fr/developpeurs/guide-migration)

**Comment by krichtof** [comment]
x attestation_fiscale_adapter.rb
x attestation_sociale_adapter.rb
x bilans_bdf_adapter.rb
x entreprise_adapter.rb
x extrait_kbis_adapter.rb
x tva_adapter.rb
x exercices_adapter.rb

rna_adapter.rb
etablissement_adapter.rb
service_adapter.rb
privileges_adapter.rb

Questions à poser à API Entreprise
[Effectifs pas dispo en v3](https://entreprise.api.gouv.fr/catalogue/urssaf/effectifs) : Est-ce que la v2 est maintenue après le 30/06/2023 ?

**Comment by skelz0r** [comment]
Je rebondis vis-à-vis du dernier commentaire: les effectifs sont maintenant dispo en v3:

* Mensuels établissements: https://entreprise.api.gouv.fr/catalogue/gip_mds/effectifs_mensuels_etablissement
* Annuels unité légale: https://entreprise.api.gouv.fr/catalogue/gip_mds/effectifs_annuels_unite_legale

Nous ne fournissons plus les effectifs mensuels pour les unités légales, car ceux-ci n'ont aucune définition (et donc valeur) légale et ne peuvent donc pas être utilisées dans des démarches. Sur la v2 il s'agissait d'une simple somme de tous les effectifs d'établissements que l'on nous fournissait, nous avions mis à disposition cette donnée, à tord. Nous vous recommandons donc de migrer sur les 2 nouvelles API et de changer vos traitements historiques vis-à-vis des effectifs mensuels d'unités légales.

A noter que les effectifs sont issues de l'URSSAF et de la MSA (ce qui n'était pas le cas en v2).

**Comment by Haelle** [comment]
Un petit UP ici.
On constate qu'il y a toujours des appels de DS sur les anciennes URL des effectifs v2 et aussi de l'ADDULACT.

Pourriez-vous refaire une passe sur le sujet ?

On va supprimer ces API fin 2023.

Merci 💪

**Comment by dzc34** [comment]
pour l'ADDULACT : ping @cmayran

**Comment by dzc34** [comment]
Salut @krichtof, 

J'ai l'impression qu'il y a encore des appels à l'API Entreprise v2.

dans [/app/lib/api_entreprise/api.rb](https://github.com/demarches-simplifiees/demarches-simplifiees.fr/blob/main/app/lib/api_entreprise/api.rb)
```ruby
class APIEntreprise::API
  ...
  PRIVILEGES_RESOURCE_NAME = "v2/privileges"
```

Cela ne va pas poser problème quand l'API entreprise v2 va être décommissionnée ?

**Comment by skelz0r** [comment]
Hello, en effet il reste des relicats.

On a introduit une nouvelle route qui est 100% iso à l'ancienne: https://entreprise.api.gouv.fr/privileges

**Comment by krichtof** [comment]
Merci @dzc34 pour la remontée et @skelz0r pour l'info. Je m'en occupe asap.

**Comment by skelz0r** [comment]
(et pas d'inquiétude on aurait dans tous les cas pas tué cette route ^^)
