### ISSUE TITLE
ETQ instructeur je voudrais pouvoir renommer mon export et renommer mes PJ (ou les préfixer/suffixer)

### ISSUE THREAD

**Issue by Bouchralazaar** [demarche-numerique/demarche.numerique.gouv.fr#9827]
Cas d'usage: un service transmet des dossiers par zip à un autre, les noms de dossiers et les pjs sont des ids incompréhensibles.

**Comment by krichtof** [comment]
L'issue reste encore à cadrer, pour l'instant, les éléments de réflexion sont posés ici : https://pad.numerique.gouv.fr/p8VUtQUHSQO4yPbYdXmRSw?edit

**Comment by krichtof** [comment]
Discussion avec @colinux 
On se dit qu'il est préférable de lier le modèle d'export à un instructeur (et non à un groupe d'instructeur) car un instructeur peut appartenir à plusieurs groupes, il pourrait avoir beaucoup de modèles d'export proposés.
ping @LeSim

**Comment by krichtof** [comment]
On se pose la question de proposer dans le nommage des fichiers, répertoires tous les tags (identité, entreprise, routage,meta-données, champs publics et champs privés). Pour les champs publics et privés, ça peut poser problème de les proposer s'il y a des révisions.
